# tasks file
---
- name: get mysql version  # noqa risky-shell-pipe
  ansible.builtin.shell: >
    mysqld --version | sed -ne 's/[^0-9]*\(\([0-9]\.\)\{0,4\}[0-9][^.]\).*/\1/p'
  register: _mysql_version
  changed_when: false
  tags:
    - configuration
    - tools
    - percona-server-tools
    - percona-server-tools-get-mysql-version

- name: reset root password < 5.7
  ansible.builtin.import_tasks: reset-root-password-lt-57.yml
  when:
    - percona_server_tools_reset_root_password.run | default(false)
    - _mysql_version.stdout is version('5.7', '<')
  tags:
    - configuration
    - tools
    - percona-server-tools
    - percona-server-tools-reset-root-password
    - percona-server-tools-reset-root-password-lt-57

- name: reset root password >= 5.7
  ansible.builtin.import_tasks: reset-root-password-ge-57.yml
  when:
    - percona_server_tools_reset_root_password.run | default(false)
    - _mysql_version.stdout is version('5.7', '>=')
  tags:
    - configuration
    - tools
    - percona-server-tools
    - percona-server-tools-reset-root-password
    - percona-server-tools-reset-root-password-ge-57

- name: reset ib_logfile
  ansible.builtin.import_tasks: reset-ib-logfile.yml
  when: percona_server_tools_reset_ib_logfile.run | default(false)
  tags:
    - configuration
    - tools
    - percona-server-tools
    - percona-server-tools-reset-ib-logfile

- name: setup slave replication
  ansible.builtin.import_tasks: setup-slave-replication.yml
  when: percona_server_tools_setup_slave_replication.run | default(false)
  tags:
    - configuration
    - tools
    - percona-server-tools
    - percona-server-tools-setup-slave-replication

- name: setup slave replication gtid
  ansible.builtin.import_tasks: setup-slave-replication-gtid.yml
  when: percona_server_tools_setup_slave_replication_gtid.run | default(false)
  tags:
    - configuration
    - tools
    - percona-server-tools
    - percona-server-tools-setup-slave-replication-gtid

- name: setup master replication
  ansible.builtin.import_tasks: setup-master-replication.yml
  when: percona_server_tools_setup_master_replication.run | default(false)
  tags:
    - configuration
    - tools
    - percona-server-tools
    - percona-server-tools-setup-master-replication
