# tasks file for percona-server-tools
---
- name: reset root password | stop service
  service:
    name: mysql
    state: stopped
  tags:
    - percona-server-tools-reset-root-password-ge-57-stop-service

- name: reset root password | start service without grants and networking
  command: >
    timeout --preserve-status 30s mysqld --skip-grant-tables --skip-networking --user=mysql
  async: 300
  poll: 0
  register: _mysqld_sleeper
  changed_when: false
  tags:
    - percona-server-tools-reset-root-password-ge-57-start-service

- name: reset root password | set password
  command: >
    mysql \
      --database=mysql \
      -e "UPDATE `user` SET `authentication_string` = PASSWORD('{{ percona_server_tools_reset_root_password.root_password }}'), plugin = 'mysql_native_password' WHERE `User` = 'root'; SELECT ROW_COUNT();" \
      --skip-column-names
  register: _rows_affected
  retries: 300
  delay: 1
  until: _rows_affected.rc == 0
  changed_when: "_rows_affected.stdout != '0'"
  tags:
    - percona-server-tools-reset-root-password-ge-57-update-password

- name: reset root password | flush privileges
  command: >
    mysql --database=mysql -e "FLUSH PRIVILEGES;"
  changed_when: false
  tags:
    - percona-server-tools-reset-root-password-ge-57-flush-privileges

- name: reset root password | wait for service to finish
  async_status:
    jid: "{{ _mysqld_sleeper.ansible_job_id }}"
  register: _mysqld_sleeper_result
  until: _mysqld_sleeper_result.finished
  retries: 300
  delay: 1
  tags:
    - percona-server-tools-reset-root-password-ge-57-end-service

- name: reset root password | start service
  service:
    name: mysql
    state: started
  tags:
    - percona-server-tools-reset-root-password-ge-57-start-service
