# tasks file
---
- name: setup master replication | check service
  ansible.builtin.service:
    name: mysql
    state: started
  tags:
    - percona-server-tools-setup-master-replication-check-service

- name: setup master replication | remove (backup) directory
  ansible.builtin.file:
    path: "{{ percona_server_tools_setup_master_replication.innobackupex.backup_dir }}"
    state: absent
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master1
  tags:
    - percona-server-tools-setup-master-replication-remove-backup-directory

- name: setup master replication | make a backup
  ansible.builtin.shell: >
    ulimit -n {{ percona_server_tools_ulimit }} && \
    innobackupex \
      --no-timestamp \
      {% if percona_server_tools_setup_master_replication.innobackupex.user is defined %}--user={{ percona_server_tools_setup_master_replication.innobackupex.user }}{% endif %} \
      {% if percona_server_tools_setup_master_replication.innobackupex.password is defined %}--password='{{ percona_server_tools_setup_master_replication.innobackupex.password }}'{% endif %} \
      {% if percona_server_tools_setup_master_replication.innobackupex.parallel is defined and percona_server_tools_setup_master_replication.innobackupex.parallel > 1 %}--parallel={{ percona_server_tools_setup_master_replication.innobackupex.parallel }}{% endif %} \
      {% if percona_server_tools_setup_master_replication.innobackupex.rsync is defined and percona_server_tools_setup_master_replication.innobackupex.rsync %}--rsync{% endif %} \
      {{ percona_server_tools_setup_master_replication.innobackupex.backup_dir }}
  register: _make_a_backup
  failed_when: "_make_a_backup.rc != 0 or _make_a_backup.stderr.split('\n')[-1].find('completed OK') == -1"
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master1
  tags:
    - percona-server-tools-setup-master-replication-make-a-backup

- name: setup master replication | prepare the backup
  ansible.builtin.shell: >
    ulimit -n {{ percona_server_tools_ulimit }} && \
    innobackupex \
      --apply-log \
      {% if percona_server_tools_setup_master_replication.innobackupex.user is defined %}--user={{ percona_server_tools_setup_master_replication.innobackupex.user }}{% endif %} \
      {% if percona_server_tools_setup_master_replication.innobackupex.password is defined %}--password='{{ percona_server_tools_setup_master_replication.innobackupex.password }}'{% endif %} \
      {% if percona_server_tools_setup_master_replication.innobackupex.use_memory is defined %}--use-memory={{ percona_server_tools_setup_master_replication.innobackupex.use_memory }}{% endif %} \
      {{ percona_server_tools_setup_master_replication.innobackupex.backup_dir }}
  register: _prepare_a_backup
  failed_when: "_prepare_a_backup.rc != 0 or _prepare_a_backup.stderr.split('\n')[-1].find('completed OK') == -1"
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master1
  tags:
    - percona-server-tools-setup-master-replication-prepare-the-backup

- name: setup master replication | get datadir
  community.mysql.mysql_variables:
    variable: datadir
  register: _datadir_value
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-get-datadir

- name: setup master replication | set datadir
  ansible.builtin.set_fact:
    percona_server_tools_datadir: "{{ _datadir_value.msg }}"
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-set-datadir

- name: setup master replication | stop slave
  community.mysql.mysql_replication:
    mode: stopslave
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-stop-slave

- name: setup master replication | reset slave
  community.mysql.mysql_replication:
    mode: resetslaveall
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-reset-slave

- name: setup master replication | stop service
  ansible.builtin.service:
    name: mysql
    state: stopped
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-stop-service

- name: setup master replication | purge datadir
  ansible.builtin.file:
    path: "{{ percona_server_tools_datadir.rstrip('/') }}"
    state: absent
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-purge-datadir

- name: setup master replication | pull backup
  ansible.builtin.command: >
    rsync
    -ai --delete
    -e 'ssh{% if percona_server_tools_setup_master_replication.ssh_opts is defined %} {{ percona_server_tools_setup_master_replication.ssh_opts | join(" ") }}{% endif %}'
    {{ percona_server_tools_setup_master_replication.master1.host }}:{{ percona_server_tools_setup_master_replication.innobackupex.backup_dir }}/
    {{ percona_server_tools_datadir.rstrip('/') }}
  register: _pull_backup
  changed_when: _pull_backup.stdout_lines | length > 0
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-pull-backup

- name: setup master replication | set permissions
  ansible.builtin.file:
    path: "{{ percona_server_tools_datadir.rstrip('/') }}"
    owner: "{{ percona_server_tools_mysqld_user }}"
    group: "{{ percona_server_tools_mysqld_user }}"
    recurse: true
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-set-permissions

- name: setup master replication | stat debian.cnf
  ansible.builtin.stat:
    path: "{{ percona_server_tools_debian_cnf_file }}"
  register: _stat_debian_cnf
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-stat-debian.cnf

- name: setup master replication | pull debian.cnf
  ansible.builtin.command: >
    rsync
    -ai --checksum --delete
    -e ssh
    {{ percona_server_tools_setup_master_replication.master1.host }}:{{ percona_server_tools_debian_cnf_file }}
    {{ percona_server_tools_debian_cnf_file }}
  register: _pull_debian_cnf
  changed_when: _pull_debian_cnf.stdout_lines | length > 0
  when:
    - inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
    - _stat_debian_cnf.stat.exists
  tags:
    - percona-server-tools-setup-master-replication-pull-debian.cnf

- name: setup master replication | start service
  ansible.builtin.service:
    name: mysql
    state: started
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-start-service

- name: setup master replication | set offline_mode to 1 (online)
  community.mysql.mysql_variables:
    variable: offline_mode
    value: '0'
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-set-offline_mode

- name: setup master replication | get master
  ansible.builtin.command: >
    cat {{ percona_server_tools_datadir.rstrip('/') }}/xtrabackup_binlog_info
  register: _master1_log_information
  changed_when: false
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-get-master

- name: setup master replication | change master
  community.mysql.mysql_replication:
    mode: changemaster
    master_host: "{{ percona_server_tools_setup_master_replication.master1.host }}"
    master_user: "{{ percona_server_tools_setup_master_replication.master1.user }}"
    master_password: "{{ percona_server_tools_setup_master_replication.master1.password }}"
    master_log_file: "{{ _master1_log_information.stdout.split()[0] }}"
    master_log_pos: "{{ _master1_log_information.stdout.split()[1] }}"
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-start-service

- name: setup master replication | start slave
  community.mysql.mysql_replication:
    mode: startslave
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  tags:
    - percona-server-tools-setup-master-replication-start-slave

- name: setup master replication | get slave
  community.mysql.mysql_replication:
    mode: getslave
  register: _slave2_information
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master2
  failed_when: _slave2_information.Slave_IO_Running != 'Yes' or _slave2_information.Slave_SQL_Running != 'Yes'
  tags:
    - percona-server-tools-setup-master-replication-get-slave

- name: setup master replication | get master
  community.mysql.mysql_replication:
    mode: getmaster
    login_host: "{{ percona_server_tools_setup_master_replication.master2.host }}"
    login_user: "{{ percona_server_tools_setup_master_replication.master2.user | default(percona_server_tools_setup_master_replication.master1.user) }}"
    login_password: "{{ percona_server_tools_setup_master_replication.master2.password | default(percona_server_tools_setup_master_replication.master1.password) }}"
  register: _master2_log_information
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master1
  tags:
    - percona-server-tools-setup-master-replication-get-master

- name: setup master replication | stop slave
  community.mysql.mysql_replication:
    mode: stopslave
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master1
  tags:
    - percona-server-tools-setup-master-replication-stop-slave

- name: setup master replication | reset slave
  community.mysql.mysql_replication:
    mode: resetslaveall
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master1
  tags:
    - percona-server-tools-setup-master-replication-reset-slave

- name: setup master replication | change master
  community.mysql.mysql_replication:
    mode: changemaster
    master_host: "{{ percona_server_tools_setup_master_replication.master2.host }}"
    master_user: "{{ percona_server_tools_setup_master_replication.master2.user | default(percona_server_tools_setup_master_replication.master1.user) }}"
    master_password: "{{ percona_server_tools_setup_master_replication.master2.password | default(percona_server_tools_setup_master_replication.master1.password) }}"
    master_log_file: "{{ _master2_log_information.File }}"
    master_log_pos: "{{ _master2_log_information.Position }}"
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master1
  tags:
    - percona-server-tools-setup-master-replication-change-master

- name: setup master replication | start slave
  community.mysql.mysql_replication:
    mode: startslave
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master1
  tags:
    - percona-server-tools-setup-master-replication-start-slave

- name: setup master replication | get slave
  community.mysql.mysql_replication:
    mode: getslave
  register: _slave1_information
  when: inventory_hostname == percona_server_tools_setup_master_replication.inventory.master1
  failed_when: _slave1_information.Slave_IO_Running != 'Yes' or _slave1_information.Slave_SQL_Running != 'Yes'
  tags:
    - percona-server-tools-setup-master-replication-get-slave
