# tasks file
---
- name: setup slave replication gtid | check | version
  ansible.builtin.fail:
    msg: "Not implemented exception"
  tags:
    - percona-server-tools-setup-slave-replication-gtid-ge-80-check-version
